name: Build Plugin
on:
  push:
    tags:
        - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest
    permissions:
        contents: write

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'

      - name: Restore
        run: dotnet restore

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
          
      - name: Build
        run: |
          dotnet build --no-restore --configuration Release --nologo

      - uses: ncipollo/release-action@v1
        with:
            artifacts: "./HoardFarm/bin/x64/Release/HoardFarm/latest.zip"
            name: ${{ github.event.head_commit.message }}
            draft: true

      - run: |
          rm -R ./HoardFarm/bin/x64/Release/HoardFarm

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest
          path: ./HoardFarm/bin/x64/Release/
